// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'

const database = process.env.DATABASE_NAME;
const host = process.env.DATABASE_HOST;
const port = process.env.DATABASE_PORT;
const user = process.env.DATABASE_USER;
const password = process.env.DATABASE_PASSWORD;

if (!database) {
  throw new Error('DATABASE_NAME is not set')
}
if (!host) {
  throw new Error('DATABASE_HOST is not set')
}
if (!port) {
  throw new Error('DATABASE_PORT is not set')
}
if (!user) {
  throw new Error('DATABASE_USER is not set')
}
if (!password) {
  throw new Error('DATABASE_PASSWORD is not set')
}

const url = `postgresql://${user}:${password}@${host}:${port}/${database}`

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: url
  }
})
