name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: NODE=development npm ci

      - name: Prisma generate
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck
